# Allows us to see all the available actuators.
management.endpoints.web.exposure.include: "*"

# Required to fix an issue with springfox-swagger
spring.mvc.pathmatch.matching-strategy: ant_path_matcher

application.print.beans.enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:userdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
